### PR TITLE
Added rules how-to stub

### PR DESCRIPTION
**Pull request by tomkyle**
I additionally added a paragraph about the Response object, since it is used inside the validate method.

### CODE REVIEW

**Comment by tomkyle** [comment]
and a typofix

**Comment by phmLabs** [comment]
Should we start to use the wiki for documentation?

**Comment by tomkyle** [comment]
Good idea, since there already are too many tests to describe them thoroughly in single README; as a propasal, we could roughly outline each rule in the README and link to its wiki page. 
(sorry, I have no clou about wikis at all, so I wouldn't be good help with it)

**Comment by digitalkaoz** [comment]
you can link multiple markdown files. i would prefer to write them all in markdown so ich can read the docs offline if i have cloned the repo. afaik you can link the wiki to some .md resources

**Comment by tomkyle** [comment]
Wiki or linked MDs, probably a matter of taste. I would prefer Robert's proposal.

**Pull request merged**
